services:
  db:
    container_name: "hw_sorter_db"
    image: mariadb
    restart: always
    ports:
      - "13306:3306"
    environment:
      MARIADB_DATABASE: hw_sorter
      MARIADB_USER: kmg
      MARIADB_PASSWORD: 1234
      MARIADB_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql